### ISSUE TITLE
Killing phpliteadmin process

### ISSUE THREAD

**Issue by hljoren** [cs50/harvard.cs50.browser#1]
phpliteadmin process isn't killed when the tab is closed

**Comment by kzidane** [comment]
@hljames apologies for the belated reply! Wasn't watching the repo for some reason! Recall which `phpliteadmin` version you were running?

**Comment by kzidane** [comment]
https://github.com/cs50/harvard.cs50.browser/issues/2#issuecomment-311528646

@hljames if using < v1.2.2, mind running

```
$ sudo apt-get update
$ sudo apt-get install phpliteadmin
```

and trying again?

You may run the following command to see which version you have installed:

```
$ apt-cache policy phpliteadmin | grep Installed
```
