### ISSUE TITLE
Error message if process already running?

### ISSUE THREAD

**Issue by hljoren** [cs50/harvard.cs50.browser#2]
If a process is already running, the tab continues trying to load indefinitely. It might be nice to instead provide the user with some kind of error message, akin to "Address already in use" when trying to run flask if flask is already running.

**Comment by dmalan** [comment]
Actually, @kzidane, we should probably presumptuously kill whatever's running on 8082, effectively letting this plugin own 8082?

**Comment by kzidane** [comment]
@dmalan, it already does that. @hljames I probably forgot to tell you to upgrade `phpliteadmin`. My bad!

![phpliteadmin-kill](https://user-images.githubusercontent.com/7230211/27616307-e62c73a4-5b7c-11e7-84d3-615358224f65.gif)
