### ISSUE TITLE
Visual display of executable files

### ISSUE THREAD

**Issue by hljoren** [cs50/harvard.cs50.browser#5]
It might be nice to change the background color of the pane with the window of the executable file to white to be closer to what the students would see in an external browser window

**Comment by dmalan** [comment]
@hljames or @kzidane, mind attaching a screenshot of what it currently looks like?

**Comment by hljoren** [comment]
![screen shot 2017-06-28 at 3 24 22 pm](https://user-images.githubusercontent.com/21977222/27656166-faff5fd2-5c15-11e7-81f4-e6e33bb8c1d0.png)

**Comment by kzidane** [comment]
![dark](https://user-images.githubusercontent.com/7230211/27686640-ac7fb442-5ca1-11e7-80d4-498efef002b4.png)
![light](https://user-images.githubusercontent.com/7230211/27686641-acd47b8a-5ca1-11e7-9018-13ea2ce76f44.png)

00c961d
